# Numpy Basics

**Numpy** es el paquete fundamental para la computacion cientifica en Python y es la base de muchos otros paquetes. Aunque sea dificil de creer, Python no fue hecho para ejecutar computaciones numericas pero cuando Python se comenzo a hacer popular en los 90's fue necesario ejecutar operaciones vectoriales mucho mas rapido de que lo Python podia hacer en ese tiempo y Numpy fue creado. Como podemos observar en la imagen Numpy es parte esencial de muchos paquetes populares en Python usados en el campo de Machine Learning. 

<img src='./data/img/numpy.jpg'>
![alt text](/data/img/numpy.jpg "numpystack")


En resumen podemos conlcuir que las ventajas de Numpy son:

- Es Open Source y gratis.
- Tiene una sintaxis muy amigable.
- Es mas eficiente que las lista de Python.
- Tiene funciones muy avanzadas y esta muy bien integrado en otras librerias.

### Instalar Numpy

Para instalar numpy simplemente ejecutamos la siguiente linea de codigo:

    - pip3 install numpy
    
Si queremos una version especifica de numpy:

    - pip3 install numpy==<version>


## Numpy Arrays

Como seguramente sabes lo que hace a Numpy muy util son las matrices multidimensionales o **ndarrays**. Un ejemplo:

In [13]:
# importamos numpy, para hacer nuestro codigo mas legible lo importamos como np
import numpy as np

x = np.array([[1,2,3,],[4,5,6]])
# imprime la matriz
print('Esta es nuestra matriz: ', (x))
# imprime el tipo de objeto que es nuestra matriz
print('Nuestra matriz es del tipo: ', type(x))
# imprime las dimensiones de la matriz
print('La dimension de nuestra matriz es: ', x.shape)
# imprime el tamano de nuestra matriz
print('El tamano de nuestra matriz es: ', x.size)
# imprime la dimension de nuestra matriz
print('La dimension de nuestra matriz es: ', x.ndim)
# imprime el tipo de dato que hay dentro de nuestra matriz
print('El tipo de dato de nuestra matriz es: ', x.dtype)
# imprime el numero de bytes que hay dentro de nuestra matriz
print('El total de bytes en nuestra matriz es: ', x.nbytes)

Esta es nuestra matriz:  [[1 2 3]
 [4 5 6]]
Nuestra matriz es del tipo:  <class 'numpy.ndarray'>
La dimension de nuestra matriz es:  (2, 3)
El tamano de nuestra matriz es:  6
La dimension de nuestra matriz es:  2
El tipo de dato de nuestra matriz es:  int64
El total de bytes en nuestra matriz es:  48


Vamos a ver que sucede cuando usamos un *float*, *complex* o *uint*: 

In [14]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.float)
print(x)
print(x.nbytes)

[[1. 2. 3.]
 [4. 5. 6.]]
48


In [15]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.complex)
print(x)
print(x.nbytes)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [16]:
x = np.array([[1,2,3],[4,-5,6]], dtype = np.uint32)
print(x)
print(x.nbytes)

[[         1          2          3]
 [         4 4294967291          6]]
24


Cada tipo consume un numero distinto de bytes:

In [17]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print("int64 consume",x.nbytes, "bytes")
x = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print("int32 consume",x.nbytes, "bytes")

int64 consume 48 bytes
int32 consume 24 bytes


Es importante tener en cuenta este tipo de cosas basicas especialmente cuando estamos hablando de Big Data en donde este tipo de conversiones es muy importante para el desempeno. Como podemos ver no podemos modificar el *dtype* de nuestra matriz una vez que la hemos creado, pero lo que si podemos hacer es copiarla y cambiar el *dtype* con el atributo *astype*, un ejemplo:

In [20]:
copia_x = np.array(x, dtype = np.float)
copia_x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
copia_x_int = copia_x.astype(np.int)
copia_x_int

array([[1, 2, 3],
       [4, 5, 6]])

**Algo muy importante que tenemos que considerar es que *astype* no cambia el *dtype* "de copia_x", lo que sucede es que conserva las condiciones originales pero crea "copia_x_int"**